### ISSUE TITLE
iPhone results as Desktop platform

### ISSUE THREAD

**Issue by Khez** [blackmirror1980/detector-js#10] opened 2019-10-24 12:15 UTC

**Comment by ghost** [comment] 2021-03-03 14:12
this should be fixed. sorry for late answer!

**Comment by ghost** [comment] 2021-03-03 14:27
anyhow if the issue is still there.... please tell me something more details.

iPhone model
iOS version
browser used (native iOS Safari or something else?)

**Closed as completed** 2021-05-19 17:13 UTC
